let time = new Date()
console.log(time)
console.dir(time)
console.log(time.getDate())
console.log(time.getTime())
console.log(time.toTimeString())
console.log(time.toLocaleString())
console.log(time.toDateString())
console.log(time.toString())
